# Generated by Django 4.0.6 on 2022-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='whatsapp_phone_no_id',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
