# Generated by Django 4.0.6 on 2022-09-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0003_userdata_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='msg_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='template_img',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='whatsapp_account_id',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
