# Generated by Django 4.0.6 on 2023-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0004_userdata_msg_limit_userdata_template_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='scheme_file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='stock_file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='file_name',
            field=models.TextField(max_length=2048),
        ),
    ]
