# Generated by Django 4.0.6 on 2023-06-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0005_userdata_scheme_file_name_userdata_stock_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='templates',
            field=models.JSONField(default=dict),
        ),
    ]
