# Generated by Django 4.0.6 on 2023-08-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0006_alter_userdata_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_App_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('fcm_id', models.CharField(blank=True, max_length=4096, null=True)),
                ('access_allowed', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='simistocks.userdata')),
            ],
        ),
    ]
