# Generated by Django 4.0.6 on 2023-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0007_manage_app_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_app_access',
            name='device_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='manage_app_access',
            name='device_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='allowed_app_user',
            field=models.IntegerField(default=0),
        ),
    ]
