# Generated by Django 4.0.6 on 2023-08-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0008_manage_app_access_device_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_app_access',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
