# Generated by Django 4.0.6 on 2024-01-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0009_alter_manage_app_access_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='blocked_number',
            field=models.JSONField(default=list),
        ),
    ]
