# Generated by Django 4.0.6 on 2024-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0010_userdata_blocked_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='access_allowed',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='otp_authentication',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='third_party_api',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
    ]
