# Generated by Django 4.0.6 on 2024-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0011_userdata_access_allowed_userdata_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
