# Generated by Django 4.0.6 on 2024-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0012_alter_userdata_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_app_access',
            name='otp_received',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='manage_app_access',
            name='otp_receiver_number',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
