# Generated by Django 4.0.6 on 2024-07-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simistocks', '0013_manage_app_access_otp_received_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='Userdata',
        ),
        migrations.CreateModel(
            name='Whatsapp_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.TextField(null=True)),
                ('data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='simistocks.userdata')),
            ],
        ),
    ]
